# Generated by Django 4.2.21 on 2025-06-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_subscriber',
            field=models.BooleanField(default=True, verbose_name='Подписан на информационные рассылки по email?'),
        ),
    ]
