# Generated by Django 4.2.21 on 2025-05-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ошибки')),
                ('image_path', models.FileField(upload_to='error_images/', verbose_name='Путь к фото')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Ошибки',
                'verbose_name_plural': 'Ошибки',
            },
        ),
    ]
